---
title: "CV"
---

**Professional Appointments**

*2025 onwards*: [Australian Research Council DECRA Fellow]{style="color: #9E96D6; font-weight: 600;"}, Australian National University.

*2023--2025:* Postdoctoral Research Fellow at the Australian National University (ANU)

*2020--2023:* Postdoctoral Researcher at the Swiss Federal Institute of Technology in Zürich (ETH Zürich) and Swiss Federal Research Institute for Forest, Snow, and Landscape (WSL)

*2019--2020:* Research Assistant at the Australian National University (ANU)

**Education**

PhD, Australian National University. July 2016 to February 2020 -- Supervised by [Marcel Cardillo](https://biology.anu.edu.au/people/academics/marcel-cardillo)

Bachelor of Science (Honours), Australian National University, Canberra, 2015.

**Publications**

Google [Scholar](https://scholar.google.com.au/citations?user=fvEE3s4AAAAJ&hl=en)

**Invited Talks**

University of Sydney, New South Wales *(2026)*

Royal Botanical Gardens, Sydney, New South Wales *(2026)*

University of Wollongong, New South Wales *(2024)*

Ecology and Evolution Seminar Series, Australian National University *(2023)*

Biogeography of Tropical Asia Symposium, National University of Singapore, Singapore *(2023)*

Center for Biodiversity and Global Change, Yale. *Understanding the evolution of biodiversity with process-based simulation models* *(2022)*

Laboratoire d'Ecologie Alpine (LECA). *Inferring the tempo and mode of speciation using simulation-based approaches* *(2022)*

British Ecological Society Macroecology Meeting, St. Andrews, United Kingdom *(2018)*, [Student Plenary Award]{style="color: #9E96D6;"}

Tempo and Mode Seminar Series, Australian National University *(2018)*

**Conference Talks and Presentations**

Australasian Evolution Society, Brisbane, Australia *(2025)*

Third Joint Congress on Evolutionary Biology, Montreal, Canada *(2024)*

AsiaEvo, Singapore *(2023)*

INTECOL 2022 \| 13th International Congress of Ecology, Geneva, Switzerland *(2022)*

Biology '22. Meeting of the Swiss Zoological, Botanical, and Systematics Societies, Basel, Switzerland *(2022)*

(Virtual) British Ecological Society Macroecology Meeting *(2021)*

(Virtual) Evolution *(2021)*

World Congress of Herpetology, Dunedin, New Zealand *(2020)*

International Biogeography Society Meeting, Malaga, Spain *(2019)*

*Poster:* Australasian Evolution Society, Sydney, Australia *(2019)*

British Ecological Society Macroecology Meeting, St. Andrews, United Kingdom *(2018)*

ANU Research School of Biology HDR Student Conference *(2016, 2017, 2018)*

**Organised Symposia**

Biotic interchanges across taxa through molecular and fossil data. 3rd Joint Congress of Evolutionary Biology, Montreal, Canada *(2024)*

**Awards and Grants**

[Discovery Early Career Research Award]{style="color: #9E96D6; font-weight: 600;"}, Australian Research Council *(2025)* -- DE250100004: *How environmental change drives the origin and decline of biodiversity* -- \$486,675

Research School of Biology Early Career Researcher Travel top-up grant, Australian National University *(2024)* -- \$2,000

Early Career Researcher Travel Grant, Australian National University *(2024)* -- \$3,000

Training Support Grant, Centre for Biodiversity Analysis *(2023)* -- \$10,000

Best Poster Award, Australasian Evolution Society Conference, UNSW *(2019)* -- \$100

Vice-Chancellor's HDR Travel Grants, Australian National University *(2019)* -- \$5,000

[Student Plenary Award]{style="color: #9E96D6;"}, British Ecological Society Macroecology Meeting, St Andrews, Scotland *(2018)* -- \$500

Graduate Student Research Award, Society of Systematic Biologists *(2018)* -- \$2,500

**Service and Leadership**

[Treasurer]{style="color: #9E96D6; font-weight: 600;"}, Australasian Evolution Society *(2026)*

[Elected Member]{style="color: #9E96D6; font-weight: 600;"}, NTEU Branch Committee *(2024--2026)*

[NTEU Delegate]{style="color: #9E96D6; font-weight: 600;"}, Research School of Biology, Australian National University *(2026)*

[Coordinator]{style="color: #9E96D6; font-weight: 600;"}, Ecology and Evolution Seminar Series, Research School of Biology, Australian National University *(2024--2026)*

**Reviews**

[Publons](https://publons.com/researcher/1565074/alexander-skeels/); Science Advances, Nature Ecology and Evolution, Nature Sustainability, PNAS, PLOS Biology, Trends in Ecology and Evolution, Biological Reviews, New Phytologist, Ecology Letters, Proceedings of the Royal Society B: Biological Sciences, Methods in Ecology and Evolution, Systematic Biology, Global Ecology and Biogeography, Evolution, Journal of Evolutionary Biology, Science of the Total Environment, Journal of Biogeography, Molecular Phylogenetics and Evolution, Biological Journal of the Linnean Society, Biodiversity and Conservation, PLOS One, Ecosphere, Ecology and Evolution, Frontiers of Biogeography.

**Workshops**

**Gen3sis: Simulating the Evolution of Biodiversity**
<br>[Center for Biodiversity Analysis, Australian National University, Canberra]{style="color: #888;"} *(30 Sep -- 2 Oct 2024)*
<br>Instructors: **Alexander Skeels**, Oskar Hagen, Tristan Salles

**Mechanistic Spatially Explicit Eco-Evolutionary Biodiversity Modelling**
<br>[yDiv, Leipzig, Germany]{style="color: #888;"} *(14--18 Nov 2022)*
<br>Instructors: Oskar Hagen, **Alexander Skeels**, Benjamin Rosenbaum, Florian Hartig

**Teaching**

*2025--2026:* [Lecturer]{style="color: #9E96D6; font-weight: 600;"}, Australian National University
<br>&nbsp;&nbsp;&nbsp;&nbsp;BIOL8002: *Advanced Topics in Quantitative Biology*
<br>&nbsp;&nbsp;&nbsp;&nbsp;BIOL3207: *Data Science for Biologists*

*2023--2024:* [Guest Lecturer]{style="color: #9E96D6; font-weight: 600;"}, Australian National University
<br>&nbsp;&nbsp;&nbsp;&nbsp;BIOL3206: *Macroevolution and Macroecology*

*2020--2023:* [Teaching Assistant]{style="color: #9E96D6; font-weight: 600;"}, ETH Zurich
<br>&nbsp;&nbsp;&nbsp;&nbsp;701-1679-00L: *Spatial Modelling: From Climate & Land Use Change to Biodiversity Conservation*

*2019:* [Guest Lecturer]{style="color: #9E96D6; font-weight: 600;"}, Australian National University
<br>&nbsp;&nbsp;&nbsp;&nbsp;BIOL3206: *Macroevolution and Macroecology*

*2016--2019:* [Teaching Assistant]{style="color: #9E96D6; font-weight: 600;"}, Australian National University
<br>&nbsp;&nbsp;&nbsp;&nbsp;BIOL3206: *Evolution of Biodiversity*
<br>&nbsp;&nbsp;&nbsp;&nbsp;ENVS1003: *Introduction to Environmental and Social Research*
<br>&nbsp;&nbsp;&nbsp;&nbsp;BIOL2161: *Principles of Genetics*
<br>&nbsp;&nbsp;&nbsp;&nbsp;BIOL8702: *Advanced Research Techniques*
