---
title: "Alex Skeels"
---

Hi there, I'm a biodiversity scientist and evolutionary biologist currently working as a postdoc in the [Macroevolution and Macroecology Group](http://www.macroevoeco.com/) at the [Australian National University](https://biology.anu.edu.au/research/divisions/ecology-and-evolution) (ANU), and will be beginning an ARC DECRA Fellowship in 2025.

I'm interested in exploring biodiversity patterns and the evolutionary histories of the plant and animal groups that contribute to them. You can find an example of my most recent research published in *Science*, [here](https://www.science.org/stoken/author-tokens/ST-1301/full).

One of my main interests is the origins of *biodiversity hotspots*, such as those found in tropical rainforests, mountain ranges, or Mediterranean-type ecosystems. I am also interested in understanding how these regions, and the organisms within them, are vulnerable to global change. To explore these topics, I analyse spatial, phylogenetic, and ecological-trait data with *simulation modelling* and *comparative* *analyses*.

Some specific questions I work on include:

\(i\) How have **historical environmental dynamics**, including climate change, plate tectonics, and mountain building, shaped evolutionary radiations and patterns of species diversity in the present-day?

\(ii\) Can we detect and use the signatures of **speciation**, **extinction**,and **geographic range evolution** dynamics in spatial and phylogenetic data to make inferences about ecological and evolutionary processes?

\(iii\) What factors drive exceptional plant diversity in **Mediterranean-Type-Ecosystems**?

\(iv\) Can we forecast **extinction risk** in vulnerable groups using spatial, phylogenetic, and trait data?

Feel free to [reach out](https://alexskeels.com/contact/) if you have any questions.
